### ISSUE TITLE
I can't use it ,below is debug info.how can i test it 

### ISSUE THREAD

**Issue by flychen50** [stonefury/aws-alfred#1]
[STDERR: alfred.workflow.input.scriptfilter] 16:45:48 entrypoint.py:17 DEBUG    ip_address
16:45:48 entrypoint.py:19 DEBUG    r
16:45:49 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:45:49 workflow.py:2008 DEBUG    Workflow finished in 1.623 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 16:45:50 entrypoint.py:17 DEBUG    ip_address
16:45:50 entrypoint.py:19 DEBUG    runnn
16:45:51 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:45:51 workflow.py:2008 DEBUG    Workflow finished in 1.725 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 16:45:55 entrypoint.py:17 DEBUG    ip_address
16:45:55 entrypoint.py:19 DEBUG    runnnn
16:45:56 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:45:56 workflow.py:2008 DEBUG    Workflow finished in 1.639 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 16:45:57 entrypoint.py:17 DEBUG    ip_address
16:45:57 entrypoint.py:19 DEBUG    runnni
16:45:58 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:45:58 workflow.py:2008 DEBUG    Workflow finished in 1.648 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 16:45:59 entrypoint.py:17 DEBUG    ip_address
16:45:59 entrypoint.py:19 DEBUG    runing
16:46:00 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:46:00 workflow.py:2008 DEBUG    Workflow finished in 1.685 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 16:46:19 entrypoint.py:17 DEBUG    id
16:46:19 entrypoint.py:19 DEBUG    i-fa648c31
16:46:21 workflow.py:2152 WARNING  Can't save last version: workflow has no version
16:46:21 workflow.py:2008 DEBUG    Workflow finished in 1.883 seconds.

**Comment by bfleming-ciena** [comment]
Hi. That warning is coming from the python workflow module and I see the same thing. I will look into that separately.

What happens when you type in ec2 find <somename> ?? What do you see instead of results?

Couple things.

If you have the aws tools installed, boto will use your creds from the ~/.aws directory.  Then I think it tries ~/.boto, or maybe the reverse. In any case, I'm curious if it is that issue.

aws configure
Or your ~/.boto file should be present.

If you're getting no results, no error, do you have instances in the region you're searching?

Do ec2 config region=us-west-2

or whatever region your instances are in.

**Comment by bfleming-ciena** [comment]
Closing for now. Let me know if you need help again.
